-- Sprint 5A: estructura vacía para atribución explícita de pedidos a campañas.
-- No crea relaciones ni modifica pedidos, costos ni campañas existentes.
-- Kommo podrá completar estos registros posteriormente con una atribución verificable.

create table if not exists public.atribuciones_campana_pedido (
  id bigint generated by default as identity primary key,
  order_id text not null unique references public.orders(order_id) on delete cascade,
  meta_campaign_id text not null,
  fuente text not null default 'kommo' check (fuente in ('kommo', 'manual', 'otro')),
  referencia_externa text,
  atribuido_en timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists atribuciones_campana_pedido_campaign_idx
  on public.atribuciones_campana_pedido (meta_campaign_id);

alter table public.atribuciones_campana_pedido enable row level security;
revoke all on table public.atribuciones_campana_pedido from anon, authenticated;

comment on table public.atribuciones_campana_pedido is
  'Relación explícita y verificable entre un pedido y una campaña de Meta. Permanece vacía hasta ser completada por Kommo u otra fuente confiable.';
comment on column public.atribuciones_campana_pedido.meta_campaign_id is
  'ID de campaña de Meta recibido desde una fuente de atribución confiable; no se infiere desde pedidos.';
