-- Sprint 3: auditoría preparada para futuras acciones sobre Meta.
-- No envía ni ejecuta cambios sobre campañas.
create table if not exists public.acciones_publicidad (
  id bigint generated by default as identity primary key,
  campaign_id text not null,
  campaign_name text not null,
  accion text not null check (accion in ('activar', 'pausar', 'cambiar_presupuesto')),
  valor_anterior jsonb,
  valor_nuevo jsonb,
  fecha timestamptz not null default now(),
  estado text not null default 'simulacion' check (estado in ('simulacion', 'pendiente_confirmacion', 'confirmada', 'ejecutada', 'cancelada', 'error')),
  confirmado_por text,
  created_at timestamptz not null default now()
);

create index if not exists acciones_publicidad_campaign_fecha_idx on public.acciones_publicidad (campaign_id, fecha desc);
alter table public.acciones_publicidad enable row level security;
revoke all on table public.acciones_publicidad from anon, authenticated;
comment on table public.acciones_publicidad is 'Registro de simulaciones y futuras acciones confirmadas sobre Meta Ads. Sprint 3 no inserta ni ejecuta acciones reales.';
