-- Sprint 2A: costos reales y utilidad por pedido.
-- Ejecuta este archivo una sola vez, después de la migración Sprint 1.
-- No modifica, elimina ni reemplaza la tabla public.orders.

create table if not exists public.costos_pedido (
  id bigint generated by default as identity primary key,
  order_id text not null unique references public.orders(order_id) on delete cascade,
  cantidad_perfumes integer not null check (cantidad_perfumes > 0),
  costo_unitario_perfume numeric(10,2) not null default 3.00 check (costo_unitario_perfume >= 0),
  costo_productos numeric(10,2) not null default 0 check (costo_productos >= 0),
  costo_empaque numeric(10,2) not null default 1.50 check (costo_empaque >= 0),
  costo_envio numeric(10,2) check (costo_envio >= 0),
  comision_vendedor numeric(10,2) not null default 0 check (comision_vendedor >= 0),
  costo_devolucion numeric(10,2) not null default 0 check (costo_devolucion >= 0),
  otros_costos numeric(10,2) not null default 0 check (otros_costos >= 0),
  utilidad_antes_publicidad numeric(10,2),
  costo_publicidad_atribuido numeric(10,2) not null default 0 check (costo_publicidad_atribuido >= 0),
  utilidad_final numeric(10,2),
  estado_calculo text not null default 'provisional' check (estado_calculo in ('provisional', 'completo', 'no_calculado')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists costos_pedido_estado_calculo_idx on public.costos_pedido (estado_calculo);

create or replace function public.calcular_costos_pedido()
returns trigger
language plpgsql
as $$
declare
  total_pedido numeric(10,2);
  estado_pedido text;
begin
  select total, status into total_pedido, estado_pedido
  from public.orders
  where order_id = new.order_id;

  new.costo_productos := round(new.cantidad_perfumes * new.costo_unitario_perfume, 2);
  new.updated_at := now();

  if estado_pedido = 'cancelado' then
    new.utilidad_antes_publicidad := null;
    new.utilidad_final := null;
    new.estado_calculo := 'no_calculado';
  elsif new.costo_envio is null then
    -- No se asume que el envío vale cero: hasta registrarlo no hay utilidad calculada.
    new.utilidad_antes_publicidad := null;
    new.utilidad_final := null;
    new.estado_calculo := 'provisional';
  else
    new.utilidad_antes_publicidad := round(
      total_pedido - new.costo_productos - new.costo_empaque - new.costo_envio
      - new.comision_vendedor - new.costo_devolucion - new.otros_costos,
      2
    );
    new.utilidad_final := round(new.utilidad_antes_publicidad - new.costo_publicidad_atribuido, 2);
    -- En este Sprint aún no existe atribución de publicidad; por eso sigue provisional.
    new.estado_calculo := 'provisional';
  end if;

  return new;
end;
$$;

drop trigger if exists costos_pedido_calcular_before_write on public.costos_pedido;
create trigger costos_pedido_calcular_before_write
before insert or update on public.costos_pedido
for each row execute function public.calcular_costos_pedido();

create or replace function public.crear_costos_pedido()
returns trigger
language plpgsql
as $$
declare
  cantidad integer;
begin
  select coalesce(sum((item ->> 'quantity')::integer), 0)
  into cantidad
  from jsonb_array_elements(new.items) as item;

  insert into public.costos_pedido (order_id, cantidad_perfumes)
  values (new.order_id, cantidad);
  return new;
end;
$$;

drop trigger if exists orders_crear_costos_after_insert on public.orders;
create trigger orders_crear_costos_after_insert
after insert on public.orders
for each row execute function public.crear_costos_pedido();

create or replace function public.actualizar_calculo_costos_por_estado()
returns trigger
language plpgsql
as $$
begin
  update public.costos_pedido
  set updated_at = now()
  where order_id = new.order_id;
  return new;
end;
$$;

drop trigger if exists orders_actualizar_costos_after_status_change on public.orders;
create trigger orders_actualizar_costos_after_status_change
after update of status on public.orders
for each row execute function public.actualizar_calculo_costos_por_estado();

-- Crea una sola ficha de costos para cada pedido existente, conservando intactos sus datos.
insert into public.costos_pedido (order_id, cantidad_perfumes)
select
  o.order_id,
  coalesce((select sum((item ->> 'quantity')::integer) from jsonb_array_elements(o.items) as item), o.item_count)
from public.orders o
where not exists (
  select 1 from public.costos_pedido c where c.order_id = o.order_id
);

alter table public.costos_pedido enable row level security;
revoke all on table public.costos_pedido from anon, authenticated;

comment on table public.costos_pedido is 'Costos reales y utilidad provisional por pedido. El envío se registra manualmente.';
