-- Ejecuta este archivo una sola vez en Supabase > SQL Editor.
-- La web inserta pedidos desde el servidor; ninguna llave privada llega al navegador.

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  created_at timestamptz not null default now(),
  customer_name text not null,
  phone text not null check (phone ~ '^09[0-9]{8}$'),
  city text not null,
  province text not null,
  address text not null,
  reference text,
  items jsonb not null check (jsonb_typeof(items) = 'array'),
  item_count integer not null check (item_count > 0),
  pricing jsonb not null check (jsonb_typeof(pricing) = 'array'),
  regular_total numeric(10,2) not null check (regular_total >= 0),
  savings numeric(10,2) not null default 0 check (savings >= 0),
  total numeric(10,2) not null check (total >= 0),
  status text not null default 'nuevo' check (status in ('nuevo', 'confirmado', 'preparando', 'enviado', 'entregado', 'cancelado')),
  payment_method text not null default 'contraentrega',
  source text not null default 'web'
);

create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_phone_idx on public.orders (phone);
create index if not exists orders_status_idx on public.orders (status);

alter table public.orders enable row level security;
revoke all on table public.orders from anon, authenticated;

comment on table public.orders is 'Pedidos contra entrega creados desde wildcollection.com';
comment on column public.orders.status is 'nuevo, confirmado, preparando, enviado, entregado o cancelado';
