"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import styles from "./publicidad.module.css";

type Campaign = { id: string; name: string; status: string; objective: string | null; daily_budget: number | null; spend_today: number; spend_week: number; spend_month: number; reach: number; impressions: number; ctr: number | null; cpm: number | null; conversations: number; cost_per_conversation: number | null; adsets: Array<{ id: string; name: string; status: string; daily_budget: number | null; ads: Array<{ id: string; name: string; status: string }> }> };
type Data = { currency: string; campaigns: Campaign[]; summary: { spend_today: number; spend_week: number; spend_month: number; conversations: number; cost_per_conversation: number | null }; updated_at: string };
type Simulation = { campaign: { id: string; name: string; status: string; daily_budget: number | null }; action: string; new_budget: number | null; requires_confirmation: boolean; execution: string };

const money = (value: number | null, currency: string) => value === null ? "No disponible" : `${currency} ${new Intl.NumberFormat("es-EC", { minimumFractionDigits: currency === "COP" ? 0 : 2, maximumFractionDigits: currency === "COP" ? 0 : 2 }).format(value)}`;
const number = (value: number) => new Intl.NumberFormat("es-EC").format(value);
const date = (value: string) => new Intl.DateTimeFormat("es-EC", { dateStyle: "medium", timeStyle: "short", timeZone: "America/Guayaquil" }).format(new Date(value));
const status = (value: string) => ({ ACTIVE: "Activa", PAUSED: "Pausada", ARCHIVED: "Archivada", DELETED: "Eliminada" }[value] ?? value);

export default function PublicidadPage() {
  const [data, setData] = useState<Data | null>(null);
  const [screen, setScreen] = useState<"loading" | "ready" | "login" | "error">("loading");
  const [error, setError] = useState(""); const [refreshing, setRefreshing] = useState(false); const [expanded, setExpanded] = useState<string | null>(null);
  const [simulation, setSimulation] = useState<Simulation | null>(null); const [budget, setBudget] = useState("");

  async function load(manual = false) { if (manual) setRefreshing(true); try { const response = await fetch("/api/admin/publicidad", { cache: "no-store" }); const body = await response.json().catch(() => ({})); if (response.status === 401) { setScreen("login"); return; } if (!response.ok) { setError(body.error ?? "No pudimos consultar Meta Ads."); setScreen("error"); return; } setData(body); setScreen("ready"); } catch { setError("No pudimos conectar con el panel."); setScreen("error"); } finally { setRefreshing(false); } }
  async function simulate(campaign: Campaign, action: "activar" | "pausar" | "cambiar_presupuesto") { const response = await fetch("/api/admin/publicidad/simulacion", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ campaign_id: campaign.id, action, new_budget: action === "cambiar_presupuesto" ? Number(budget) : undefined }) }); const body = await response.json().catch(() => ({})); if (!response.ok) { setError(body.error ?? "No pudimos preparar la simulación."); return; } setSimulation(body.simulation); }
  useEffect(() => { void load(); }, []);
  if (screen === "loading") return <main className={styles.centered}><div className={styles.mark}>WC</div><p>Consultando Meta Ads</p></main>;
  if (screen === "login") return <main className={styles.centered}><section className={styles.notice}><p className={styles.eyebrow}>Acceso privado</p><h1>Inicia sesión para ver la publicidad.</h1><Link href="/admin/pedidos">Ir a pedidos →</Link></section></main>;
  if (screen === "error") return <main className={styles.centered}><section className={styles.notice}><p className={styles.eyebrow}>Meta Ads no disponible</p><h1>No pudimos cargar los datos.</h1><p className={styles.error}>{error}</p><button type="button" onClick={() => void load()}>Intentar de nuevo</button></section></main>;
  return <main className={styles.dashboard}>
    <header className={styles.header}><Link href="/" className={styles.brand}><span>WC</span><b>Wild Collection</b></Link><div className={styles.title}><small>Panel privado</small><strong>Publicidad</strong></div><nav><Link href="/admin/resumen">Resumen</Link><Link href="/admin/pedidos">Pedidos</Link><Link href="/">Ver tienda</Link></nav></header>
    <div className={styles.inner}><section className={styles.intro}><div><p className={styles.eyebrow}>Wild Ads Control</p><h1>La pauta,<br /><em>con claridad.</em></h1></div><div><p>Consumo publicitario real de Meta. Este módulo no muestra cobros a tu tarjeta y no puede cambiar campañas todavía.</p><button type="button" onClick={() => void load(true)} disabled={refreshing}>{refreshing ? "Actualizando…" : "Actualizar datos"}</button><small>Última actualización: {date(data!.updated_at)}</small></div></section>
      <section className={styles.summary}><article><small>Gasto hoy</small><strong>{money(data!.summary.spend_today, data!.currency)}</strong></article><article><small>Gasto semana</small><strong>{money(data!.summary.spend_week, data!.currency)}</strong></article><article><small>Gasto mes</small><strong>{money(data!.summary.spend_month, data!.currency)}</strong></article><article><small>Conversaciones del mes</small><strong>{number(data!.summary.conversations)}</strong></article><article><small>Costo promedio por conversación</small><strong>{money(data!.summary.cost_per_conversation, data!.currency)}</strong></article></section>
      <section className={styles.section}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>Información de Meta</p><h2>Campañas</h2></div><p>{data!.campaigns.length} encontradas · Moneda: {data!.currency}</p></div>{data!.campaigns.length === 0 ? <div className={styles.empty}>No hay campañas disponibles en esta cuenta publicitaria.</div> : <div className={styles.list}>{data!.campaigns.map((campaign) => <article className={styles.campaign} key={campaign.id}><div className={styles.campaignTop}><div><span className={`${styles.badge} ${campaign.status === "ACTIVE" ? styles.active : ""}`}>{status(campaign.status)}</span><h3>{campaign.name}</h3><p>{campaign.objective ?? "Objetivo no disponible"} · ID {campaign.id}</p></div><button type="button" className={styles.details} onClick={() => setExpanded(expanded === campaign.id ? null : campaign.id)}>{expanded === campaign.id ? "Ocultar detalle" : "Ver conjuntos y anuncios"}</button></div><div className={styles.metrics}><div><small>Presupuesto diario</small><b>{money(campaign.daily_budget, data!.currency)}</b></div><div><small>Gasto hoy</small><b>{money(campaign.spend_today, data!.currency)}</b></div><div><small>Gasto semana</small><b>{money(campaign.spend_week, data!.currency)}</b></div><div><small>Gasto mes</small><b>{money(campaign.spend_month, data!.currency)}</b></div><div><small>Alcance</small><b>{number(campaign.reach)}</b></div><div><small>Impresiones</small><b>{number(campaign.impressions)}</b></div><div><small>CTR</small><b>{campaign.ctr === null ? "No disponible" : `${campaign.ctr.toFixed(2)}%`}</b></div><div><small>CPM</small><b>{money(campaign.cpm, data!.currency)}</b></div><div><small>Conversaciones</small><b>{number(campaign.conversations)}</b></div><div><small>Costo por conversación</small><b>{money(campaign.cost_per_conversation, data!.currency)}</b></div></div>
        <div className={styles.simulate}><span>Simulación segura</span><button type="button" onClick={() => void simulate(campaign, "activar")}>Simular activar</button><button type="button" onClick={() => void simulate(campaign, "pausar")}>Simular pausar</button><input value={budget} onChange={(event) => setBudget(event.target.value)} inputMode="decimal" placeholder="Nuevo presupuesto diario" aria-label="Nuevo presupuesto diario"/><button type="button" onClick={() => void simulate(campaign, "cambiar_presupuesto")}>Simular presupuesto</button></div>
        {expanded === campaign.id && <div className={styles.children}>{campaign.adsets.length === 0 ? <p>No hay conjuntos disponibles.</p> : campaign.adsets.map((adset) => <div key={adset.id}><strong>Conjunto: {adset.name}</strong><small>{status(adset.status)} · Presupuesto diario: {money(adset.daily_budget, data!.currency)}</small>{adset.ads.length ? <ul>{adset.ads.map((ad) => <li key={ad.id}>{ad.name} <span>{status(ad.status)}</span></li>)}</ul> : <p>Sin anuncios disponibles.</p>}</div>)}</div>}
      </article>)}</div>}</section>
      {simulation && <section className={styles.modal} role="dialog" aria-modal="true"><div><p className={styles.eyebrow}>Confirmación requerida</p><h2>Revisa la acción propuesta</h2><p><b>Campaña:</b> {simulation.campaign.name}</p><p><b>Estado actual:</b> {status(simulation.campaign.status)} · <b>Presupuesto actual:</b> {money(simulation.campaign.daily_budget, data!.currency)}</p><p><b>Acción propuesta:</b> {simulation.action === "cambiar_presupuesto" ? `Cambiar el presupuesto diario a ${money(simulation.new_budget, data!.currency)}` : simulation.action === "activar" ? "Activar campaña" : "Pausar campaña"}</p><p className={styles.warning}>{simulation.execution} La ejecución real se habilitará solo en el Sprint 4.</p><button type="button" onClick={() => setSimulation(null)}>Entendido</button></div></section>}
    </div></main>;
}
